### ISSUE TITLE
Trailing comma being added

### ISSUE THREAD

**Issue by wesleycoder** [peterjuras/vsc-sort-imports#13]
A trailing comma is being added when we declare an import like follows.
input:
```js
import {
  CHANGE_TAB,
  ADD_TAB
} from './actions';
```

actual behavior:
```js
import {
  ADD_TAB,
  CHANGE_TAB, // this trailing comma is being added
} from './actions';
```

expected:
```js
import {
  ADD_TAB,
  CHANGE_TAB // no trailing comma added
} from './actions';
```

**Comment by peterjuras** [comment]
Hi!

This is due to the parsing output of the [import-sort](https://github.com/renke/import-sort) module and is sadly currently [not configurable](https://github.com/renke/import-sort/issues/7) :(

Feel free to open a pull request if this is a blocking issue for you, trailing commas are there by default to [make diffs easier to read](https://dnlserrano.github.io/2015/07/29/a-case-for-trailing-commas/).
