### ISSUE TITLE
Taking over project

### ISSUE THREAD

**Issue by ferdaber** [peterjuras/vsc-sort-imports#27]
Hi, it looks like this project isn't being maintained anymore or you're looking for another maintainer. I'd be happy to take over as this is something my team needs to use with a bit more configuration.

**Comment by johncloud200** [comment]
do it bro0o Q(^_^)Q

at issue #15, owner said "I can't work on this project anymore and I'm on the search for a new maintainer for this extension"

**Comment by johncloud200** [comment]
do it bro0o Q(^_^)Q

**Comment by Alxandr** [comment]
Would love to get some updates for this again :). I really love the plugin, but it keeps failing on certain things I really need (like dynamic imports, or flow opaque types).

**Comment by peterjuras** [comment]
This extension has been taken over by a new maintainer, please reopen your pull request under the [new repository.](https://github.com/amatiasq/vsc-sort-imports)

**Comment by Alxandr** [comment]
We can't open issues in that project.

**Comment by robyoder** [comment]
Wow, this is really frustrating. An extension that was working just fine autoupdates and says it's deprecated, then recommends a different extension, which is different from the original (including at least one bug) but no way to open issues.

**Comment by peterjuras** [comment]
Sorry for the trouble. @amatiasmq could you open issues on your repo? You can tick a box in the settings of your repository.

**Comment by ChiefORZ** [comment]
The switch over to a new engine (amq-sort-imports) is too harsh... it works now completely different as the original plugin was previously...

revert these changes please and make the use of the "amq-sort-imports" an option - not an forced changed for all ppl that are using this extension already.

**Comment by ChiefORZ** [comment]
@peterjuras i would recommend you inviting multiple collaborators to this project and let them as a group decide which changes can be made, and which one not.

**Comment by peterjuras** [comment]
I'm sorry for all the trouble, I republished the extension without a deprecation popup under version 3.0.1, so people should not have such a bad experience upgrading.

Is someone else interested in taking over this project, with backwards compatible configuration? I sadly don't have time to deal with this a lot, so it would be good if someone just makes an easy upgrade path from the current extension.

**Comment by amatiasq** [comment]
@Alxandr @robyoder I'm sorry by that, forks don't have issues by default, I didn't know that. They're enabled now.

@ChiefORZ The new version is not `amq-sort-imports`. That one is also deprecated [as you can see](https://marketplace.visualstudio.com/items?itemName=amatiasq.amq-sort-imports). The new version is [`sort-imports`](https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports).

**Comment by ChiefORZ** [comment]
@amatiasq as @peterjuras mentioned, your new package is not backward compatible and is working on a new sorting algorithm now... this change is too harsh in my opinion. some people maybe like the way the extension was sorting the imports (https://github.com/renke/import-sort/tree/master/packages/import-sort-style-eslint). Your PR changed the way things were sorted completely and not compatible with ESLint rules in any way.
This is a move our team is not willing to make unfortunately.

Hopefully the old project stays in the marketplace the way it is, because it is working the way it is.

**Comment by amatiasq** [comment]
@ChiefORZ Yes, that was an intentional change. I created this fork months ago to add an option so users can have different types of sorting, it was set as the default option long before this project was announced as unmaintained and to change it now will break it for all users who are using the new version since it was published.

If you check [the README file](https://github.com/amatiasq/vsc-sort-imports/#extension-settings) you'll find the new option `sort-imports.sort-type`, as the documentation says possible values are:

- `by-module-name` will sort imports by the imported path. This is the default setting.
- `by-imported-name` will sort the imports by the first imported identifier.

The sorting method of this project is what in the new project is called `by-imported-name`, you can just set that configuration option.

**Comment by robyoder** [comment]
Filed https://github.com/amatiasq/vsc-sort-imports/issues/2
