### ISSUE TITLE
Custom sort

### ISSUE THREAD

**Issue by brunolemos** [peterjuras/vsc-sort-imports#3]
Using the Airbnb ESLlint rules, we face the following error: 
`Absolute imports should come before relative imports.` ([import/first](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md))

Instead of asking you to change the sort algorithm to fit this use case, it would be better to have a way to customize that.

**Comment by peterjuras** [comment]
Customizing the sort style is valuable feature, and @renke added it to the newest release of the VSCode extension. After updating to version 2.1.0 you can customize the styling of the imports in the package.json of your project. For more information, check out the [documentation of the import-sort package](https://marketplace.visualstudio.com/items?itemName=peterjuras.sort-imports).

Since the _absolutes-first_ order is a common requirement, I also started the discussion of adjusting the default import style to be in accordance with the airbnb eslint rules. [Feel free to voice your opinion there as well.](https://github.com/renke/import-sort/issues/9)

**Comment by sergeyzwezdin** [comment]
@peterjuras @renke  Just added this config into `package.json` and nothing changed. Could you point me where I'm wrong?
```
{
    "name": "...",
    "version": ...,
    ....,
    "importSort": {
        ".js, .jsx, .es6, .es": {
            "parser": "babylon",
            "style": "module"
        },
        ".ts, .tsx": {
            "parser": "typescript",
            "style": "module"
        }
    }
}
```
